### ISSUE TITLE
Remove components directory

### ISSUE THREAD

**Issue by filipecorrea** [IBM/libras#22]
**Is your feature request related to a problem? Please describe.**
There're no other components in `src/components` to justify the use of this directory.

**Describe the solution you'd like**
The `src/components/logger.js` file should be moved to `src/logger/index.js`.

**Comment by marcobarrera** [comment]
May I work on this issue?

**Comment by filipecorrea** [comment]
Hi @marcobarrera. Sure! Feel free to check ou our CONTRIBUTING guide to know what to do next. Please let me know if you have any questions.
