### ISSUE TITLE
Improve the way we handle ambiguity 

### ISSUE THREAD

**Issue by crissm** [IBM/libras#4]
For example 
The following registered phrase:

igreja aborto proibir.
It brings many possibilities:

["O aborto proíbe a igreja.","O guidão da igreja quebrou.","Desculpem-me, a proibição é um aborto.","Na Bahia, o aborto das pessoas é negro.","igreja adora proibição.","O aborto da gasolina aumentou.","A igreja comprou uma proibição."]

**Comment by filipecorrea** [comment]
Let's close this issue for a moment until we complete #2. I don't want external contributors to get confused about it.
